name: Main

on:
  # weekly
  schedule:
    - cron: 0 0 * * 0
  # on-demand
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.branch || 'master' }}
    - name: Greeting
      run: echo 'Hello world'